// AUTO-GENERATED by scripts/gen-docs-manifest.mjs, do not edit by hand.
// Regenerate with: node scripts/gen-docs-manifest.mjs

export interface DocsManifestEntry {
  name: string;
  slug: string;
  description: string;
  category: string;
}

export const docsManifest: DocsManifestEntry[] = [
  {
    "name": "Accordion",
    "slug": "accordion",
    "description": "",
    "category": "layout"
  },
  {
    "name": "Alert",
    "slug": "alert",
    "description": "",
    "category": "feedback"
  },
  {
    "name": "Alert Dialog",
    "slug": "alert-dialog",
    "description": "Tracks the Root's onOpenChange so AlertDialogContent can close the",
    "category": "feedback"
  },
  {
    "name": "Avatar",
    "slug": "avatar",
    "description": "Avatar behavior.",
    "category": "data-display"
  },
  {
    "name": "Avatar Group",
    "slug": "avatar-group",
    "description": "",
    "category": "data-display"
  },
  {
    "name": "Badge",
    "slug": "badge",
    "description": "",
    "category": "data-display"
  },
  {
    "name": "Breadcrumb",
    "slug": "breadcrumb",
    "description": "",
    "category": "layout"
  },
  {
    "name": "Button",
    "slug": "button",
    "description": "",
    "category": "data-display"
  },
  {
    "name": "Button Group",
    "slug": "button-group",
    "description": "",
    "category": "data-display"
  },
  {
    "name": "Card",
    "slug": "card",
    "description": "",
    "category": "data-display"
  },
  {
    "name": "Checkbox",
    "slug": "checkbox",
    "description": "",
    "category": "inputs"
  },
  {
    "name": "Collapsible",
    "slug": "collapsible",
    "description": "Collapsible: expand/collapse section built on Radix Collapsible primitive.",
    "category": "layout"
  },
  {
    "name": "Color Picker",
    "slug": "color-picker",
    "description": "ColorPicker: native color swatch plus validated hex text input.",
    "category": "ready-to-use"
  },
  {
    "name": "Combobox",
    "slug": "combobox",
    "description": "",
    "category": "inputs"
  },
  {
    "name": "Command",
    "slug": "command",
    "description": "",
    "category": "general"
  },
  {
    "name": "Context Menu",
    "slug": "context-menu",
    "description": "",
    "category": "feedback"
  },
  {
    "name": "Country Code Input",
    "slug": "country-code-input",
    "description": "CountryCodeInput: a phone number input with a leading country-code",
    "category": "inputs"
  },
  {
    "name": "Data Table",
    "slug": "data-table",
    "description": "DataTable: a ready-to-use data table built on the facet Table primitives.",
    "category": "data-display"
  },
  {
    "name": "Date Picker",
    "slug": "date-picker",
    "description": "DatePicker: an in-house calendar date picker built on the facet Popover",
    "category": "inputs"
  },
  {
    "name": "Dialog",
    "slug": "dialog",
    "description": "",
    "category": "feedback"
  },
  {
    "name": "Dropdown Menu",
    "slug": "dropdown-menu",
    "description": "",
    "category": "feedback"
  },
  {
    "name": "Dropzone",
    "slug": "dropzone",
    "description": "Dropzone: click or drag-and-drop file upload area with keyboard support.",
    "category": "ready-to-use"
  },
  {
    "name": "Empty State",
    "slug": "empty-state",
    "description": "",
    "category": "feedback"
  },
  {
    "name": "Form",
    "slug": "form",
    "description": "Form: lightweight react-hook-form + zod field wrapper.",
    "category": "inputs"
  },
  {
    "name": "Hover Card",
    "slug": "hover-card",
    "description": "",
    "category": "feedback"
  },
  {
    "name": "Input",
    "slug": "input",
    "description": "",
    "category": "inputs"
  },
  {
    "name": "Input Otp",
    "slug": "input-otp",
    "description": "",
    "category": "inputs"
  },
  {
    "name": "Kbd",
    "slug": "kbd",
    "description": "Render the platform modifier key (⌘ on macOS, Ctrl elsewhere)",
    "category": "data-display"
  },
  {
    "name": "Label",
    "slug": "label",
    "description": "",
    "category": "inputs"
  },
  {
    "name": "Location Picker",
    "slug": "location-picker",
    "description": "LocationPicker: cascading Country → State/Region → LGA/Locality",
    "category": "inputs"
  },
  {
    "name": "Marquee",
    "slug": "marquee",
    "description": "Marquee: auto-scrolling horizontal ticker with pause-on-hover support.",
    "category": "ready-to-use"
  },
  {
    "name": "Menubar",
    "slug": "menubar",
    "description": "",
    "category": "layout"
  },
  {
    "name": "Navbar",
    "slug": "navbar",
    "description": "Active-state matching for plain anchors:",
    "category": "layout"
  },
  {
    "name": "Navigation Menu",
    "slug": "navigation-menu",
    "description": "",
    "category": "layout"
  },
  {
    "name": "Notification Drawer",
    "slug": "notification-drawer",
    "description": "",
    "category": "data-display"
  },
  {
    "name": "Number Input",
    "slug": "number-input",
    "description": "NumberInput: a numeric input with spin buttons and min/max/step",
    "category": "inputs"
  },
  {
    "name": "Pagination",
    "slug": "pagination",
    "description": "",
    "category": "layout"
  },
  {
    "name": "Popover",
    "slug": "popover",
    "description": "",
    "category": "feedback"
  },
  {
    "name": "Progress",
    "slug": "progress",
    "description": "",
    "category": "feedback"
  },
  {
    "name": "Qrcode",
    "slug": "qrcode",
    "description": "QRCode: render a value as a scannable QR code.",
    "category": "ready-to-use"
  },
  {
    "name": "Radio Group",
    "slug": "radio-group",
    "description": "",
    "category": "inputs"
  },
  {
    "name": "Roadmap",
    "slug": "roadmap",
    "description": "Roadmap: vertical timeline of feature items with status badges.",
    "category": "ready-to-use"
  },
  {
    "name": "Scroll Area",
    "slug": "scroll-area",
    "description": "",
    "category": "layout"
  },
  {
    "name": "Select",
    "slug": "select",
    "description": "",
    "category": "inputs"
  },
  {
    "name": "Separator",
    "slug": "separator",
    "description": "",
    "category": "layout"
  },
  {
    "name": "Sheet",
    "slug": "sheet",
    "description": "",
    "category": "layout"
  },
  {
    "name": "Skeleton",
    "slug": "skeleton",
    "description": "",
    "category": "feedback"
  },
  {
    "name": "Slider",
    "slug": "slider",
    "description": "",
    "category": "inputs"
  },
  {
    "name": "Sonner",
    "slug": "sonner",
    "description": "Toaster: styled sonner toast provider.",
    "category": "feedback"
  },
  {
    "name": "Spinner",
    "slug": "spinner",
    "description": "",
    "category": "feedback"
  },
  {
    "name": "Switch",
    "slug": "switch",
    "description": "",
    "category": "inputs"
  },
  {
    "name": "Table",
    "slug": "table",
    "description": "",
    "category": "data-display"
  },
  {
    "name": "Tabs",
    "slug": "tabs",
    "description": "",
    "category": "layout"
  },
  {
    "name": "Textarea",
    "slug": "textarea",
    "description": "",
    "category": "inputs"
  },
  {
    "name": "Toggle",
    "slug": "toggle",
    "description": "",
    "category": "inputs"
  },
  {
    "name": "Toggle Group",
    "slug": "toggle-group",
    "description": "",
    "category": "inputs"
  },
  {
    "name": "Tooltip",
    "slug": "tooltip",
    "description": "",
    "category": "feedback"
  },
  {
    "name": "Icon",
    "slug": "icon",
    "description": "Semantic icon registry: built-in lucide map, registerIcon overrides, IconProvider per-domain overrides.",
    "category": "foundations"
  },
  {
    "name": "Theme",
    "slug": "theme",
    "description": "ThemeProvider / useTheme / ThemeToggle: light, dark, and system theming.",
    "category": "foundations"
  }
];
