/**
 * AUTO-GENERATED by scripts/gen-icon-map.mjs (via the semantic-keys drift guard):
 * DO NOT EDIT BY HAND.
 *
 * Direct (tree-shakeable) imports for the ~30 lucide icons the component UI
 * resolves by semantic name. Emitting them as direct imports (instead of
 * reading them out of the 1,500-entry `lucideIconMap` at runtime) means any
 * consumer using the built-in semantic icons never pulls the full catalog —
 * the 1,500-icon map is only loaded lazily for arbitrary lucide names
 * ("heart", ...). See registry.tsx. Regenerate with:
 *
 *   node scripts/gen-icon-map.mjs
 */
import {
  Settings,
  LogOut,
  ChevronDown,
  Search,
  Check,
  Moon,
  Sun,
  Bell,
  Menu,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  Sparkles,
  BookOpen,
  Building,
  Users,
  Shield,
  CreditCard,
  LayoutDashboard,
  FileText,
  CircleQuestionMark,
  LayoutGrid,
  List,
  TriangleAlert,
  Copy,
  ChevronsUpDown,
  Compass,
  Layers,
  Palette,
  KeyRound,
  User,
  Upload,
  QrCode,
  Trash,
} from "lucide-react";
import type { IconComponent } from "../registry.js";

export const SEMANTIC_ICONS: Partial<Record<string, IconComponent>> = {
  "settings": Settings,
  "logout": LogOut,
  "chevron-down": ChevronDown,
  "search": Search,
  "check": Check,
  "moon": Moon,
  "sun": Sun,
  "bell": Bell,
  "menu": Menu,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "arrow-right": ArrowRight,
  "sparkles": Sparkles,
  "book-open": BookOpen,
  "building": Building,
  "users": Users,
  "shield": Shield,
  "credit-card": CreditCard,
  "dashboard": LayoutDashboard,
  "document": FileText,
  "help": CircleQuestionMark,
  "grid": LayoutGrid,
  "list": List,
  "triangle-alert": TriangleAlert,
  "copy": Copy,
  "chevron-up-down": ChevronsUpDown,
  "compass": Compass,
  "layers": Layers,
  "palette": Palette,
  "key-round": KeyRound,
  "user": User,
  "upload": Upload,
  "qrcode": QrCode,
  "trash": Trash,
};

