/**
 * Static location dataset for LocationPicker: countries, regions
 * (states/provinces), and localities (LGAs). Resolved dynamically by
 * country -> region -> locality in the picker. See location-picker.tsx.
 */

export interface Country {
  /** ISO alpha-2 country code. */
  code: string;
  name: string;
}

export interface Region {
  /** Region/state id within the country. */
  id: string;
  name: string;
}

export interface Locality {
  /** Locality/LGA id within the region. */
  id: string;
  name: string;
}

/**
 * The term each country uses for its first-level division (what the
 * "state" select shows). Falls back to "region".
 */
export const REGION_LABELS: Record<string, string> = {
  NG: "state",
  US: "state",
  IN: "state",
  BR: "state",
  MX: "state",
  AU: "state",
  KE: "county",
  IE: "county",
  GB: "country",
  GH: "region",
  TZ: "region",
  ET: "region",
  UG: "region",
  RW: "province",
  ZA: "province",
  CN: "province",
  EG: "governorate",
  SA: "region",
  AE: "emirate",
  CA: "province",
  JP: "prefecture",
};

/**
 * The term each country uses for its second-level division (what the
 * "LGA/locality" select shows). Falls back to "locality".
 */
export const LOCALITY_LABELS: Record<string, string> = {
  NG: "LGA",
  US: "county",
  KE: "sub-county",
  GB: "district",
  GH: "district",
  IN: "district",
  CN: "county",
  BR: "municipality",
  JP: "municipality",
};

/** Resolve the region term for a country (e.g. "NG" -> "state"). */
export function getRegionLabel(country?: string): string {
  return (country && REGION_LABELS[country]) || "region";
}

/** Resolve the locality term for a country (e.g. "NG" -> "LGA"). */
export function getLocalityLabel(country?: string): string {
  return (country && LOCALITY_LABELS[country]) || "locality";
}

/**
 * Bundled static dataset — every African country plus the major
 * non-African markets.
 */
export const DEFAULT_COUNTRIES: Country[] = [
  /* Africa (all 54) */
  { code: "DZ", name: "Algeria" },
  { code: "AO", name: "Angola" },
  { code: "BJ", name: "Benin" },
  { code: "BW", name: "Botswana" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "CV", name: "Cabo Verde" },
  { code: "CM", name: "Cameroon" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "DR Congo" },
  { code: "CI", name: "Côte d'Ivoire" },
  { code: "DJ", name: "Djibouti" },
  { code: "EG", name: "Egypt" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "SZ", name: "Eswatini" },
  { code: "ET", name: "Ethiopia" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GH", name: "Ghana" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "KE", name: "Kenya" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libya" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "ML", name: "Mali" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "NA", name: "Namibia" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "RW", name: "Rwanda" },
  { code: "ST", name: "São Tomé and Príncipe" },
  { code: "SN", name: "Senegal" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "SS", name: "South Sudan" },
  { code: "SD", name: "Sudan" },
  { code: "TZ", name: "Tanzania" },
  { code: "TG", name: "Togo" },
  { code: "TN", name: "Tunisia" },
  { code: "UG", name: "Uganda" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" },
  /* Rest of the world */
  { code: "US", name: "United States" },
  { code: "GB", name: "United Kingdom" },
  { code: "CA", name: "Canada" },
  { code: "AU", name: "Australia" },
  { code: "IN", name: "India" },
  { code: "CN", name: "China" },
  { code: "JP", name: "Japan" },
  { code: "BR", name: "Brazil" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "AE", name: "United Arab Emirates" },
];

/**
 * Region (state/province) data per country. Nigeria has all 36 states +
 * FCT; other countries list major regions.
 */
export const DEFAULT_REGIONS: Record<string, Region[]> = {
US: [
    { id: "alabama", name: "Alabama" },
    { id: "alaska", name: "Alaska" },
    { id: "arizona", name: "Arizona" },
    { id: "arkansas", name: "Arkansas" },
    { id: "california", name: "California" },
    { id: "colorado", name: "Colorado" },
    { id: "connecticut", name: "Connecticut" },
    { id: "delaware", name: "Delaware" },
    { id: "florida", name: "Florida" },
    { id: "georgia", name: "Georgia" },
    { id: "hawaii", name: "Hawaii" },
    { id: "idaho", name: "Idaho" },
    { id: "illinois", name: "Illinois" },
    { id: "indiana", name: "Indiana" },
    { id: "iowa", name: "Iowa" },
    { id: "kansas", name: "Kansas" },
    { id: "kentucky", name: "Kentucky" },
    { id: "louisiana", name: "Louisiana" },
    { id: "maine", name: "Maine" },
    { id: "maryland", name: "Maryland" },
    { id: "massachusetts", name: "Massachusetts" },
    { id: "michigan", name: "Michigan" },
    { id: "minnesota", name: "Minnesota" },
    { id: "mississippi", name: "Mississippi" },
    { id: "missouri", name: "Missouri" },
    { id: "montana", name: "Montana" },
    { id: "nebraska", name: "Nebraska" },
    { id: "nevada", name: "Nevada" },
    { id: "new-hampshire", name: "New Hampshire" },
    { id: "new-jersey", name: "New Jersey" },
    { id: "new-mexico", name: "New Mexico" },
    { id: "new-york", name: "New York" },
    { id: "north-carolina", name: "North Carolina" },
    { id: "north-dakota", name: "North Dakota" },
    { id: "ohio", name: "Ohio" },
    { id: "oklahoma", name: "Oklahoma" },
    { id: "oregon", name: "Oregon" },
    { id: "pennsylvania", name: "Pennsylvania" },
    { id: "rhode-island", name: "Rhode Island" },
    { id: "south-carolina", name: "South Carolina" },
    { id: "south-dakota", name: "South Dakota" },
    { id: "tennessee", name: "Tennessee" },
    { id: "texas", name: "Texas" },
    { id: "utah", name: "Utah" },
    { id: "vermont", name: "Vermont" },
    { id: "virginia", name: "Virginia" },
    { id: "washington", name: "Washington" },
    { id: "west-virginia", name: "West Virginia" },
    { id: "wisconsin", name: "Wisconsin" },
    { id: "wyoming", name: "Wyoming" },
    { id: "district-of-columbia", name: "District of Columbia" },
  ],
  GB: [
    { id: "england", name: "England" },
    { id: "scotland", name: "Scotland" },
    { id: "wales", name: "Wales" },
    { id: "northern-ireland", name: "Northern Ireland" },
  ],
  GH: [
    { id: "greater-accra", name: "Greater Accra" },
    { id: "ashanti", name: "Ashanti" },
    { id: "western", name: "Western" },
    { id: "central", name: "Central" },
    { id: "eastern", name: "Eastern" },
    { id: "volta", name: "Volta" },
    { id: "northern", name: "Northern" },
    { id: "upper-east", name: "Upper East" },
    { id: "upper-west", name: "Upper West" },
    { id: "bono", name: "Bono" },
    { id: "bono-east", name: "Bono East" },
    { id: "ahafo", name: "Ahafo" },
    { id: "savannah", name: "Savannah" },
    { id: "north-east", name: "North East" },
    { id: "oti", name: "Oti" },
    { id: "western-north", name: "Western North" },
  ],
  KE: [
    { id: "nairobi", name: "Nairobi" },
    { id: "mombasa", name: "Mombasa" },
    { id: "kisumu", name: "Kisumu" },
    { id: "nakuru", name: "Nakuru" },
    { id: "uasin-gishu", name: "Uasin Gishu" },
    { id: "kiambu", name: "Kiambu" },
    { id: "machakos", name: "Machakos" },
    { id: "kajiado", name: "Kajiado" },
    { id: "garissa", name: "Garissa" },
    { id: "wajir", name: "Wajir" },
    { id: "mandera", name: "Mandera" },
    { id: "marsabit", name: "Marsabit" },
    { id: "turkana", name: "Turkana" },
    { id: "west-pokot", name: "West Pokot" },
    { id: "samburu", name: "Samburu" },
    { id: "trans-nzoia", name: "Trans Nzoia" },
    { id: "bungoma", name: "Bungoma" },
    { id: "kakamega", name: "Kakamega" },
    { id: "vihiga", name: "Vihiga" },
    { id: "busia", name: "Busia" },
    { id: "siaya", name: "Siaya" },
    { id: "homa-bay", name: "Homa Bay" },
    { id: "migori", name: "Migori" },
    { id: "kisii", name: "Kisii" },
    { id: "nyamira", name: "Nyamira" },
    { id: "kericho", name: "Kericho" },
    { id: "bomet", name: "Bomet" },
    { id: "narok", name: "Narok" },
    { id: "laikipia", name: "Laikipia" },
    { id: "meru", name: "Meru" },
    { id: "tharaka-nithi", name: "Tharaka-Nithi" },
    { id: "embu", name: "Embu" },
    { id: "kitui", name: "Kitui" },
    { id: "makueni", name: "Makueni" },
    { id: "nyeri", name: "Nyeri" },
    { id: "kirinyaga", name: "Kirinyaga" },
    { id: "murang-a", name: "Murang'a" },
    { id: "nyandarua", name: "Nyandarua" },
    { id: "baringo", name: "Baringo" },
    { id: "elgeyo-marakwet", name: "Elgeyo-Marakwet" },
    { id: "nandi", name: "Nandi" },
    { id: "taita-taveta", name: "Taita-Taveta" },
    { id: "tana-river", name: "Tana River" },
    { id: "lamu", name: "Lamu" },
    { id: "kilifi", name: "Kilifi" },
    { id: "kwale", name: "Kwale" },
    { id: "isiolo", name: "Isiolo" },
  ],
  ZA: [
    { id: "gauteng", name: "Gauteng" },
    { id: "western-cape", name: "Western Cape" },
    { id: "kwazulu-natal", name: "KwaZulu-Natal" },
    { id: "eastern-cape", name: "Eastern Cape" },
    { id: "limpopo", name: "Limpopo" },
    { id: "mpumalanga", name: "Mpumalanga" },
    { id: "north-west", name: "North West" },
    { id: "northern-cape", name: "Northern Cape" },
    { id: "free-state", name: "Free State" },
  ],
  EG: [
    { id: "cairo", name: "Cairo" },
    { id: "alexandria", name: "Alexandria" },
    { id: "giza", name: "Giza" },
    { id: "port-said", name: "Port Said" },
    { id: "suez", name: "Suez" },
    { id: "luxor", name: "Luxor" },
    { id: "aswan", name: "Aswan" },
    { id: "asyut", name: "Asyut" },
    { id: "beheira", name: "Beheira" },
    { id: "beni-suef", name: "Beni Suef" },
    { id: "dakahlia", name: "Dakahlia" },
    { id: "damietta", name: "Damietta" },
    { id: "faiyum", name: "Faiyum" },
    { id: "gharbia", name: "Gharbia" },
    { id: "ismailia", name: "Ismailia" },
    { id: "kafr-el-sheikh", name: "Kafr El Sheikh" },
    { id: "matrouh", name: "Matrouh" },
    { id: "minya", name: "Minya" },
    { id: "monufia", name: "Monufia" },
    { id: "new-valley", name: "New Valley" },
    { id: "qena", name: "Qena" },
    { id: "red-sea", name: "Red Sea" },
    { id: "sharqia", name: "Sharqia" },
    { id: "sohag", name: "Sohag" },
    { id: "south-sinai", name: "South Sinai" },
    { id: "north-sinai", name: "North Sinai" },
    { id: "helwan", name: "Helwan" },
  ],
  ET: [
    { id: "addis-ababa", name: "Addis Ababa" },
    { id: "afar", name: "Afar" },
    { id: "amhara", name: "Amhara" },
    { id: "benishangul-gumuz", name: "Benishangul-Gumuz" },
    { id: "dire-dawa", name: "Dire Dawa" },
    { id: "gambela", name: "Gambela" },
    { id: "harari", name: "Harari" },
    { id: "oromia", name: "Oromia" },
    { id: "sidama", name: "Sidama" },
    { id: "somali", name: "Somali" },
    { id: "south-west", name: "South West" },
    { id: "tigray", name: "Tigray" },
  ],
  TZ: [
    { id: "dar-es-salaam", name: "Dar es Salaam" },
    { id: "dodoma", name: "Dodoma" },
    { id: "arusha", name: "Arusha" },
    { id: "mwanza", name: "Mwanza" },
    { id: "mbeya", name: "Mbeya" },
    { id: "morogoro", name: "Morogoro" },
    { id: "tanga", name: "Tanga" },
    { id: "kilimanjaro", name: "Kilimanjaro" },
    { id: "tabora", name: "Tabora" },
    { id: "kigoma", name: "Kigoma" },
    { id: "shinyanga", name: "Shinyanga" },
    { id: "kagera", name: "Kagera" },
    { id: "manyara", name: "Manyara" },
    { id: "rukwa", name: "Rukwa" },
    { id: "ruvuma", name: "Ruvuma" },
    { id: "iringa", name: "Iringa" },
    { id: "singida", name: "Singida" },
    { id: "pwani", name: "Pwani" },
    { id: "lindi", name: "Lindi" },
    { id: "mtwara", name: "Mtwara" },
    { id: "mara", name: "Mara" },
    { id: "geita", name: "Geita" },
    { id: "simiyu", name: "Simiyu" },
    { id: "songwe", name: "Songwe" },
    { id: "njombe", name: "Njombe" },
    { id: "katavi", name: "Katavi" },
    { id: "zanzibar-north", name: "Zanzibar North" },
    { id: "zanzibar-south", name: "Zanzibar South" },
    { id: "zanzibar-west", name: "Zanzibar West" },
    { id: "pemba-north", name: "Pemba North" },
    { id: "pemba-south", name: "Pemba South" },
  ],
  UG: [
    { id: "central-region", name: "Central Region" },
    { id: "eastern-region", name: "Eastern Region" },
    { id: "northern-region", name: "Northern Region" },
    { id: "western-region", name: "Western Region" },
  ],
  RW: [
    { id: "kigali", name: "Kigali" },
    { id: "eastern-province", name: "Eastern Province" },
    { id: "western-province", name: "Western Province" },
    { id: "northern-province", name: "Northern Province" },
    { id: "southern-province", name: "Southern Province" },
  ],
  IN: [
    { id: "andhra-pradesh", name: "Andhra Pradesh" },
    { id: "arunachal-pradesh", name: "Arunachal Pradesh" },
    { id: "assam", name: "Assam" },
    { id: "bihar", name: "Bihar" },
    { id: "chhattisgarh", name: "Chhattisgarh" },
    { id: "goa", name: "Goa" },
    { id: "gujarat", name: "Gujarat" },
    { id: "haryana", name: "Haryana" },
    { id: "himachal-pradesh", name: "Himachal Pradesh" },
    { id: "jharkhand", name: "Jharkhand" },
    { id: "karnataka", name: "Karnataka" },
    { id: "kerala", name: "Kerala" },
    { id: "madhya-pradesh", name: "Madhya Pradesh" },
    { id: "maharashtra", name: "Maharashtra" },
    { id: "manipur", name: "Manipur" },
    { id: "meghalaya", name: "Meghalaya" },
    { id: "mizoram", name: "Mizoram" },
    { id: "nagaland", name: "Nagaland" },
    { id: "odisha", name: "Odisha" },
    { id: "punjab", name: "Punjab" },
    { id: "rajasthan", name: "Rajasthan" },
    { id: "sikkim", name: "Sikkim" },
    { id: "tamil-nadu", name: "Tamil Nadu" },
    { id: "telangana", name: "Telangana" },
    { id: "tripura", name: "Tripura" },
    { id: "uttar-pradesh", name: "Uttar Pradesh" },
    { id: "uttarakhand", name: "Uttarakhand" },
    { id: "west-bengal", name: "West Bengal" },
    { id: "andaman-and-nicobar-islands", name: "Andaman and Nicobar Islands" },
    { id: "chandigarh", name: "Chandigarh" },
    { id: "dadra-and-nagar-haveli-and-daman-and-diu", name: "Dadra and Nagar Haveli and Daman and Diu" },
    { id: "delhi", name: "Delhi" },
    { id: "jammu-and-kashmir", name: "Jammu and Kashmir" },
    { id: "ladakh", name: "Ladakh" },
    { id: "lakshadweep", name: "Lakshadweep" },
    { id: "puducherry", name: "Puducherry" },
  ],
  CN: [
    { id: "beijing", name: "Beijing" },
    { id: "shanghai", name: "Shanghai" },
    { id: "guangdong", name: "Guangdong" },
    { id: "sichuan", name: "Sichuan" },
    { id: "shandong", name: "Shandong" },
    { id: "henan", name: "Henan" },
    { id: "hubei", name: "Hubei" },
    { id: "hunan", name: "Hunan" },
    { id: "jiangsu", name: "Jiangsu" },
    { id: "zhejiang", name: "Zhejiang" },
    { id: "fujian", name: "Fujian" },
    { id: "anhui", name: "Anhui" },
    { id: "jiangxi", name: "Jiangxi" },
    { id: "hebei", name: "Hebei" },
    { id: "shanxi", name: "Shanxi" },
    { id: "shaanxi", name: "Shaanxi" },
    { id: "gansu", name: "Gansu" },
    { id: "qinghai", name: "Qinghai" },
    { id: "guizhou", name: "Guizhou" },
    { id: "yunnan", name: "Yunnan" },
    { id: "hainan", name: "Hainan" },
    { id: "liaoning", name: "Liaoning" },
    { id: "jilin", name: "Jilin" },
    { id: "heilongjiang", name: "Heilongjiang" },
    { id: "inner-mongolia", name: "Inner Mongolia" },
    { id: "guangxi", name: "Guangxi" },
    { id: "ningxia", name: "Ningxia" },
    { id: "xinjiang", name: "Xinjiang" },
    { id: "tibet", name: "Tibet" },
    { id: "chongqing", name: "Chongqing" },
    { id: "tianjin", name: "Tianjin" },
    { id: "hong-kong", name: "Hong Kong" },
    { id: "macau", name: "Macau" },
    { id: "taiwan", name: "Taiwan" },
  ],
  BR: [
    { id: "s-o-paulo", name: "São Paulo" },
    { id: "rio-de-janeiro", name: "Rio de Janeiro" },
    { id: "minas-gerais", name: "Minas Gerais" },
    { id: "bahia", name: "Bahia" },
    { id: "paran", name: "Paraná" },
    { id: "rio-grande-do-sul", name: "Rio Grande do Sul" },
    { id: "pernambuco", name: "Pernambuco" },
    { id: "cear", name: "Ceará" },
    { id: "par", name: "Pará" },
    { id: "amazonas", name: "Amazonas" },
    { id: "maranh-o", name: "Maranhão" },
    { id: "goi-s", name: "Goiás" },
    { id: "santa-catarina", name: "Santa Catarina" },
    { id: "para-ba", name: "Paraíba" },
    { id: "esp-rito-santo", name: "Espírito Santo" },
    { id: "rio-grande-do-norte", name: "Rio Grande do Norte" },
    { id: "alagoas", name: "Alagoas" },
    { id: "mato-grosso", name: "Mato Grosso" },
    { id: "mato-grosso-do-sul", name: "Mato Grosso do Sul" },
    { id: "piau", name: "Piauí" },
    { id: "distrito-federal", name: "Distrito Federal" },
    { id: "sergipe", name: "Sergipe" },
    { id: "rond-nia", name: "Rondônia" },
    { id: "tocantins", name: "Tocantins" },
    { id: "acre", name: "Acre" },
    { id: "amap", name: "Amapá" },
    { id: "roraima", name: "Roraima" },
  ],
  SA: [
    { id: "riyadh", name: "Riyadh" },
    { id: "jeddah", name: "Jeddah" },
    { id: "mecca", name: "Mecca" },
    { id: "medina", name: "Medina" },
    { id: "eastern-province", name: "Eastern Province" },
    { id: "asir", name: "Asir" },
    { id: "tabuk", name: "Tabuk" },
    { id: "hail", name: "Hail" },
    { id: "northern-borders", name: "Northern Borders" },
    { id: "jazan", name: "Jazan" },
    { id: "najran", name: "Najran" },
    { id: "al-bahah", name: "Al-Bahah" },
    { id: "al-jawf", name: "Al-Jawf" },
  ],
  AE: [
    { id: "dubai", name: "Dubai" },
    { id: "abu-dhabi", name: "Abu Dhabi" },
    { id: "sharjah", name: "Sharjah" },
    { id: "ajman", name: "Ajman" },
    { id: "ras-al-khaimah", name: "Ras Al Khaimah" },
    { id: "fujairah", name: "Fujairah" },
    { id: "umm-al-quwain", name: "Umm Al Quwain" },
  ],
};

/**
 * Locality (LGA) data per country + region. Nigeria carries the full
 * official 774-LGA dataset; other countries ship illustrative entries.
 * Ids are state-scoped so they are unique across the dataset.
 */
export const DEFAULT_LOCALITIES: Record<string, Record<string, Locality[]>> = {
NG: {
    "abia": [
      { id: "abia-aba-north", name: "Aba North" },
      { id: "abia-aba-south", name: "Aba South" },
      { id: "abia-arochukwu", name: "Arochukwu" },
      { id: "abia-bende", name: "Bende" },
      { id: "abia-ikwuano", name: "Ikwuano" },
      { id: "abia-isiala-ngwa-north", name: "Isiala Ngwa North" },
      { id: "abia-isiala-ngwa-south", name: "Isiala Ngwa South" },
      { id: "abia-isuikwuato", name: "Isuikwuato" },
      { id: "abia-obi-ngwa", name: "Obi Ngwa" },
      { id: "abia-ohafia", name: "Ohafia" },
      { id: "abia-osisioma", name: "Osisioma" },
      { id: "abia-ugwunagbo", name: "Ugwunagbo" },
      { id: "abia-ukwa-east", name: "Ukwa East" },
      { id: "abia-ukwa-west", name: "Ukwa West" },
      { id: "abia-umuahia-north", name: "Umuahia North" },
      { id: "abia-umuahia-south", name: "Umuahia South" },
      { id: "abia-umu-nneochi", name: "Umu Nneochi" },
    ],
    "adamawa": [
      { id: "adamawa-demsa", name: "Demsa" },
      { id: "adamawa-fufure", name: "Fufure" },
      { id: "adamawa-ganye", name: "Ganye" },
      { id: "adamawa-gayuk", name: "Gayuk" },
      { id: "adamawa-gombi", name: "Gombi" },
      { id: "adamawa-grie", name: "Grie" },
      { id: "adamawa-hong", name: "Hong" },
      { id: "adamawa-jada", name: "Jada" },
      { id: "adamawa-lamurde", name: "Lamurde" },
      { id: "adamawa-madagali", name: "Madagali" },
      { id: "adamawa-maiha", name: "Maiha" },
      { id: "adamawa-mayo-belwa", name: "Mayo Belwa" },
      { id: "adamawa-michika", name: "Michika" },
      { id: "adamawa-mubi-north", name: "Mubi North" },
      { id: "adamawa-mubi-south", name: "Mubi South" },
      { id: "adamawa-numan", name: "Numan" },
      { id: "adamawa-shelleng", name: "Shelleng" },
      { id: "adamawa-song", name: "Song" },
      { id: "adamawa-toungo", name: "Toungo" },
      { id: "adamawa-yola-north", name: "Yola North" },
      { id: "adamawa-yola-south", name: "Yola South" },
    ],
    "akwa-ibom": [
      { id: "akwa-ibom-abak", name: "Abak" },
      { id: "akwa-ibom-eastern-obolo", name: "Eastern Obolo" },
      { id: "akwa-ibom-eket", name: "Eket" },
      { id: "akwa-ibom-esit-eket", name: "Esit Eket" },
      { id: "akwa-ibom-essien-udim", name: "Essien Udim" },
      { id: "akwa-ibom-etim-ekpo", name: "Etim Ekpo" },
      { id: "akwa-ibom-etinan", name: "Etinan" },
      { id: "akwa-ibom-ibeno", name: "Ibeno" },
      { id: "akwa-ibom-ibesikpo-asutan", name: "Ibesikpo Asutan" },
      { id: "akwa-ibom-ibiono-ibom", name: "Ibiono-Ibom" },
      { id: "akwa-ibom-ika", name: "Ika" },
      { id: "akwa-ibom-ikono", name: "Ikono" },
      { id: "akwa-ibom-ikot-abasi", name: "Ikot Abasi" },
      { id: "akwa-ibom-ikot-ekpene", name: "Ikot Ekpene" },
      { id: "akwa-ibom-ini", name: "Ini" },
      { id: "akwa-ibom-itu", name: "Itu" },
      { id: "akwa-ibom-mbo", name: "Mbo" },
      { id: "akwa-ibom-mkpat-enin", name: "Mkpat-Enin" },
      { id: "akwa-ibom-nsit-atai", name: "Nsit-Atai" },
      { id: "akwa-ibom-nsit-ibom", name: "Nsit-Ibom" },
      { id: "akwa-ibom-nsit-ubium", name: "Nsit-Ubium" },
      { id: "akwa-ibom-obot-akara", name: "Obot Akara" },
      { id: "akwa-ibom-okobo", name: "Okobo" },
      { id: "akwa-ibom-onna", name: "Onna" },
      { id: "akwa-ibom-oron", name: "Oron" },
      { id: "akwa-ibom-oruk-anam", name: "Oruk Anam" },
      { id: "akwa-ibom-udung-uko", name: "Udung-Uko" },
      { id: "akwa-ibom-ukanafun", name: "Ukanafun" },
      { id: "akwa-ibom-uruan", name: "Uruan" },
      { id: "akwa-ibom-urue-offong-oruko", name: "Urue-Offong/Oruko" },
      { id: "akwa-ibom-uyo", name: "Uyo" },
    ],
    "anambra": [
      { id: "anambra-aguata", name: "Aguata" },
      { id: "anambra-anambra-east", name: "Anambra East" },
      { id: "anambra-anambra-west", name: "Anambra West" },
      { id: "anambra-anaocha", name: "Anaocha" },
      { id: "anambra-awka-north", name: "Awka North" },
      { id: "anambra-awka-south", name: "Awka South" },
      { id: "anambra-ayamelum", name: "Ayamelum" },
      { id: "anambra-dunukofia", name: "Dunukofia" },
      { id: "anambra-ekwusigo", name: "Ekwusigo" },
      { id: "anambra-idemili-north", name: "Idemili North" },
      { id: "anambra-idemili-south", name: "Idemili South" },
      { id: "anambra-ihiala", name: "Ihiala" },
      { id: "anambra-njikoka", name: "Njikoka" },
      { id: "anambra-nnewi-north", name: "Nnewi North" },
      { id: "anambra-nnewi-south", name: "Nnewi South" },
      { id: "anambra-ogbaru", name: "Ogbaru" },
      { id: "anambra-onitsha-north", name: "Onitsha North" },
      { id: "anambra-onitsha-south", name: "Onitsha South" },
      { id: "anambra-orumba-north", name: "Orumba North" },
      { id: "anambra-orumba-south", name: "Orumba South" },
      { id: "anambra-oyi", name: "Oyi" },
    ],
    "bauchi": [
      { id: "bauchi-alkaleri", name: "Alkaleri" },
      { id: "bauchi-bauchi", name: "Bauchi" },
      { id: "bauchi-bogoro", name: "Bogoro" },
      { id: "bauchi-damban", name: "Damban" },
      { id: "bauchi-darazo", name: "Darazo" },
      { id: "bauchi-dass", name: "Dass" },
      { id: "bauchi-gamawa", name: "Gamawa" },
      { id: "bauchi-ganjuwa", name: "Ganjuwa" },
      { id: "bauchi-giade", name: "Giade" },
      { id: "bauchi-itas-gadau", name: "Itas/Gadau" },
      { id: "bauchi-jama-are", name: "Jama'are" },
      { id: "bauchi-katagum", name: "Katagum" },
      { id: "bauchi-kirfi", name: "Kirfi" },
      { id: "bauchi-misau", name: "Misau" },
      { id: "bauchi-ningi", name: "Ningi" },
      { id: "bauchi-shira", name: "Shira" },
      { id: "bauchi-tafawa-balewa", name: "Tafawa Balewa" },
      { id: "bauchi-toro", name: "Toro" },
      { id: "bauchi-warji", name: "Warji" },
      { id: "bauchi-zaki", name: "Zaki" },
    ],
    "bayelsa": [
      { id: "bayelsa-brass", name: "Brass" },
      { id: "bayelsa-ekeremor", name: "Ekeremor" },
      { id: "bayelsa-kolokuma-opokuma", name: "Kolokuma/Opokuma" },
      { id: "bayelsa-nembe", name: "Nembe" },
      { id: "bayelsa-ogbia", name: "Ogbia" },
      { id: "bayelsa-sagbama", name: "Sagbama" },
      { id: "bayelsa-southern-ijaw", name: "Southern Ijaw" },
      { id: "bayelsa-yenagoa", name: "Yenagoa" },
    ],
    "benue": [
      { id: "benue-agatu", name: "Agatu" },
      { id: "benue-apa", name: "Apa" },
      { id: "benue-ado", name: "Ado" },
      { id: "benue-buruku", name: "Buruku" },
      { id: "benue-gboko", name: "Gboko" },
      { id: "benue-guma", name: "Guma" },
      { id: "benue-gwer-east", name: "Gwer East" },
      { id: "benue-gwer-west", name: "Gwer West" },
      { id: "benue-katsina-ala", name: "Katsina-Ala" },
      { id: "benue-konshisha", name: "Konshisha" },
      { id: "benue-kwande", name: "Kwande" },
      { id: "benue-logo", name: "Logo" },
      { id: "benue-makurdi", name: "Makurdi" },
      { id: "benue-obi", name: "Obi" },
      { id: "benue-ogbadibo", name: "Ogbadibo" },
      { id: "benue-ohimini", name: "Ohimini" },
      { id: "benue-oju", name: "Oju" },
      { id: "benue-okpokwu", name: "Okpokwu" },
      { id: "benue-otukpo", name: "Otukpo" },
      { id: "benue-tarka", name: "Tarka" },
      { id: "benue-ukum", name: "Ukum" },
      { id: "benue-ushongo", name: "Ushongo" },
      { id: "benue-vandeikya", name: "Vandeikya" },
    ],
    "borno": [
      { id: "borno-abadam", name: "Abadam" },
      { id: "borno-askira-uba", name: "Askira/Uba" },
      { id: "borno-bama", name: "Bama" },
      { id: "borno-bayo", name: "Bayo" },
      { id: "borno-biu", name: "Biu" },
      { id: "borno-chibok", name: "Chibok" },
      { id: "borno-damboa", name: "Damboa" },
      { id: "borno-dikwa", name: "Dikwa" },
      { id: "borno-gubio", name: "Gubio" },
      { id: "borno-guzamala", name: "Guzamala" },
      { id: "borno-gwoza", name: "Gwoza" },
      { id: "borno-hawul", name: "Hawul" },
      { id: "borno-jere", name: "Jere" },
      { id: "borno-kaga", name: "Kaga" },
      { id: "borno-kala-balge", name: "Kala/Balge" },
      { id: "borno-konduga", name: "Konduga" },
      { id: "borno-kukawa", name: "Kukawa" },
      { id: "borno-kwaya-kusar", name: "Kwaya Kusar" },
      { id: "borno-mafa", name: "Mafa" },
      { id: "borno-magumeri", name: "Magumeri" },
      { id: "borno-maiduguri", name: "Maiduguri" },
      { id: "borno-marte", name: "Marte" },
      { id: "borno-mobbar", name: "Mobbar" },
      { id: "borno-monguno", name: "Monguno" },
      { id: "borno-ngala", name: "Ngala" },
      { id: "borno-nganzai", name: "Nganzai" },
      { id: "borno-shani", name: "Shani" },
    ],
    "cross-river": [
      { id: "cross-river-abi", name: "Abi" },
      { id: "cross-river-akamkpa", name: "Akamkpa" },
      { id: "cross-river-akpabuyo", name: "Akpabuyo" },
      { id: "cross-river-bakassi", name: "Bakassi" },
      { id: "cross-river-bekwarra", name: "Bekwarra" },
      { id: "cross-river-biase", name: "Biase" },
      { id: "cross-river-boki", name: "Boki" },
      { id: "cross-river-calabar-municipal", name: "Calabar Municipal" },
      { id: "cross-river-calabar-south", name: "Calabar South" },
      { id: "cross-river-etung", name: "Etung" },
      { id: "cross-river-ikom", name: "Ikom" },
      { id: "cross-river-obanliku", name: "Obanliku" },
      { id: "cross-river-obubra", name: "Obubra" },
      { id: "cross-river-obudu", name: "Obudu" },
      { id: "cross-river-odukpani", name: "Odukpani" },
      { id: "cross-river-ogoja", name: "Ogoja" },
      { id: "cross-river-yakurr", name: "Yakurr" },
      { id: "cross-river-yala", name: "Yala" },
    ],
    "delta": [
      { id: "delta-aniocha-north", name: "Aniocha North" },
      { id: "delta-aniocha-south", name: "Aniocha South" },
      { id: "delta-bomadi", name: "Bomadi" },
      { id: "delta-burutu", name: "Burutu" },
      { id: "delta-ethiope-east", name: "Ethiope East" },
      { id: "delta-ethiope-west", name: "Ethiope West" },
      { id: "delta-ika-north-east", name: "Ika North East" },
      { id: "delta-ika-south", name: "Ika South" },
      { id: "delta-isoko-north", name: "Isoko North" },
      { id: "delta-isoko-south", name: "Isoko South" },
      { id: "delta-ndokwa-east", name: "Ndokwa East" },
      { id: "delta-ndokwa-west", name: "Ndokwa West" },
      { id: "delta-okpe", name: "Okpe" },
      { id: "delta-oshimili-north", name: "Oshimili North" },
      { id: "delta-oshimili-south", name: "Oshimili South" },
      { id: "delta-patani", name: "Patani" },
      { id: "delta-sapele", name: "Sapele" },
      { id: "delta-udu", name: "Udu" },
      { id: "delta-ughelli-north", name: "Ughelli North" },
      { id: "delta-ughelli-south", name: "Ughelli South" },
      { id: "delta-ukwuani", name: "Ukwuani" },
      { id: "delta-uvwie", name: "Uvwie" },
      { id: "delta-warri-north", name: "Warri North" },
      { id: "delta-warri-south", name: "Warri South" },
      { id: "delta-warri-south-west", name: "Warri South West" },
    ],
    "ebonyi": [
      { id: "ebonyi-abakaliki", name: "Abakaliki" },
      { id: "ebonyi-afikpo-north", name: "Afikpo North" },
      { id: "ebonyi-afikpo-south", name: "Afikpo South" },
      { id: "ebonyi-ebonyi", name: "Ebonyi" },
      { id: "ebonyi-ezza-north", name: "Ezza North" },
      { id: "ebonyi-ezza-south", name: "Ezza South" },
      { id: "ebonyi-ikwo", name: "Ikwo" },
      { id: "ebonyi-ishielu", name: "Ishielu" },
      { id: "ebonyi-ivo", name: "Ivo" },
      { id: "ebonyi-izzi", name: "Izzi" },
      { id: "ebonyi-ohaozara", name: "Ohaozara" },
      { id: "ebonyi-ohaukwu", name: "Ohaukwu" },
      { id: "ebonyi-onicha", name: "Onicha" },
    ],
    "edo": [
      { id: "edo-akoko-edo", name: "Akoko-Edo" },
      { id: "edo-egor", name: "Egor" },
      { id: "edo-esan-central", name: "Esan Central" },
      { id: "edo-esan-north-east", name: "Esan North-East" },
      { id: "edo-esan-south-east", name: "Esan South-East" },
      { id: "edo-esan-west", name: "Esan West" },
      { id: "edo-etsako-central", name: "Etsako Central" },
      { id: "edo-etsako-east", name: "Etsako East" },
      { id: "edo-etsako-west", name: "Etsako West" },
      { id: "edo-igueben", name: "Igueben" },
      { id: "edo-ikpoba-okha", name: "Ikpoba-Okha" },
      { id: "edo-oredo", name: "Oredo" },
      { id: "edo-orhionmwon", name: "Orhionmwon" },
      { id: "edo-ovia-north-east", name: "Ovia North-East" },
      { id: "edo-ovia-south-west", name: "Ovia South-West" },
      { id: "edo-owan-east", name: "Owan East" },
      { id: "edo-owan-west", name: "Owan West" },
      { id: "edo-uhunmwonde", name: "Uhunmwonde" },
    ],
    "ekiti": [
      { id: "ekiti-ado-ekiti", name: "Ado Ekiti" },
      { id: "ekiti-efon", name: "Efon" },
      { id: "ekiti-ekiti-east", name: "Ekiti East" },
      { id: "ekiti-ekiti-south-west", name: "Ekiti South-West" },
      { id: "ekiti-ekiti-west", name: "Ekiti West" },
      { id: "ekiti-emure", name: "Emure" },
      { id: "ekiti-gbonyin", name: "Gbonyin" },
      { id: "ekiti-ido-osi", name: "Ido Osi" },
      { id: "ekiti-ijero", name: "Ijero" },
      { id: "ekiti-ikere", name: "Ikere" },
      { id: "ekiti-ikole", name: "Ikole" },
      { id: "ekiti-ilejemeje", name: "Ilejemeje" },
      { id: "ekiti-irepodun-ifelodun", name: "Irepodun/Ifelodun" },
      { id: "ekiti-ise-orun", name: "Ise/Orun" },
      { id: "ekiti-moba", name: "Moba" },
      { id: "ekiti-oye", name: "Oye" },
    ],
    "enugu": [
      { id: "enugu-aninri", name: "Aninri" },
      { id: "enugu-awgu", name: "Awgu" },
      { id: "enugu-enugu-east", name: "Enugu East" },
      { id: "enugu-enugu-north", name: "Enugu North" },
      { id: "enugu-enugu-south", name: "Enugu South" },
      { id: "enugu-ezeagu", name: "Ezeagu" },
      { id: "enugu-igbo-etiti", name: "Igbo Etiti" },
      { id: "enugu-igbo-eze-north", name: "Igbo Eze North" },
      { id: "enugu-igbo-eze-south", name: "Igbo Eze South" },
      { id: "enugu-isi-uzo", name: "Isi Uzo" },
      { id: "enugu-nkanu-east", name: "Nkanu East" },
      { id: "enugu-nkanu-west", name: "Nkanu West" },
      { id: "enugu-nsukka", name: "Nsukka" },
      { id: "enugu-oji-river", name: "Oji River" },
      { id: "enugu-udenu", name: "Udenu" },
      { id: "enugu-udi", name: "Udi" },
      { id: "enugu-uzo-uwani", name: "Uzo-Uwani" },
    ],
    "gombe": [
      { id: "gombe-akko", name: "Akko" },
      { id: "gombe-balanga", name: "Balanga" },
      { id: "gombe-billiri", name: "Billiri" },
      { id: "gombe-dukku", name: "Dukku" },
      { id: "gombe-funakaye", name: "Funakaye" },
      { id: "gombe-gombe", name: "Gombe" },
      { id: "gombe-kaltungo", name: "Kaltungo" },
      { id: "gombe-kwami", name: "Kwami" },
      { id: "gombe-nafada", name: "Nafada" },
      { id: "gombe-shongom", name: "Shongom" },
      { id: "gombe-yamaltu-deba", name: "Yamaltu/Deba" },
    ],
    "imo": [
      { id: "imo-aboh-mbaise", name: "Aboh Mbaise" },
      { id: "imo-ahiazu-mbaise", name: "Ahiazu Mbaise" },
      { id: "imo-ehime-mbano", name: "Ehime Mbano" },
      { id: "imo-ezinihitte", name: "Ezinihitte" },
      { id: "imo-ideato-north", name: "Ideato North" },
      { id: "imo-ideato-south", name: "Ideato South" },
      { id: "imo-ihitte-uboma", name: "Ihitte/Uboma" },
      { id: "imo-ikeduru", name: "Ikeduru" },
      { id: "imo-isiala-mbano", name: "Isiala Mbano" },
      { id: "imo-isu", name: "Isu" },
      { id: "imo-mbaitoli", name: "Mbaitoli" },
      { id: "imo-ngor-okpala", name: "Ngor Okpala" },
      { id: "imo-njaba", name: "Njaba" },
      { id: "imo-nkwerre", name: "Nkwerre" },
      { id: "imo-nwangele", name: "Nwangele" },
      { id: "imo-obowo", name: "Obowo" },
      { id: "imo-oguta", name: "Oguta" },
      { id: "imo-ohaji-egbema", name: "Ohaji/Egbema" },
      { id: "imo-okigwe", name: "Okigwe" },
      { id: "imo-onuimo", name: "Onuimo" },
      { id: "imo-orlu", name: "Orlu" },
      { id: "imo-orsu", name: "Orsu" },
      { id: "imo-oru-east", name: "Oru East" },
      { id: "imo-oru-west", name: "Oru West" },
      { id: "imo-owerri-municipal", name: "Owerri Municipal" },
      { id: "imo-owerri-north", name: "Owerri North" },
      { id: "imo-owerri-west", name: "Owerri West" },
      { id: "imo-unuimo", name: "Unuimo" },
    ],
    "jigawa": [
      { id: "jigawa-auyo", name: "Auyo" },
      { id: "jigawa-babura", name: "Babura" },
      { id: "jigawa-biriniwa", name: "Biriniwa" },
      { id: "jigawa-birnin-kudu", name: "Birnin Kudu" },
      { id: "jigawa-buji", name: "Buji" },
      { id: "jigawa-dutse", name: "Dutse" },
      { id: "jigawa-gagarawa", name: "Gagarawa" },
      { id: "jigawa-garki", name: "Garki" },
      { id: "jigawa-gumel", name: "Gumel" },
      { id: "jigawa-guri", name: "Guri" },
      { id: "jigawa-gwaram", name: "Gwaram" },
      { id: "jigawa-gwiwa", name: "Gwiwa" },
      { id: "jigawa-hadejia", name: "Hadejia" },
      { id: "jigawa-jahun", name: "Jahun" },
      { id: "jigawa-kafin-hausa", name: "Kafin Hausa" },
      { id: "jigawa-kaugama", name: "Kaugama" },
      { id: "jigawa-kazaure", name: "Kazaure" },
      { id: "jigawa-kiri-kasama", name: "Kiri Kasama" },
      { id: "jigawa-kiyawa", name: "Kiyawa" },
      { id: "jigawa-maigatari", name: "Maigatari" },
      { id: "jigawa-malam-madori", name: "Malam Madori" },
      { id: "jigawa-miga", name: "Miga" },
      { id: "jigawa-ringim", name: "Ringim" },
      { id: "jigawa-roni", name: "Roni" },
      { id: "jigawa-sule-tankarkar", name: "Sule Tankarkar" },
      { id: "jigawa-taura", name: "Taura" },
      { id: "jigawa-yankwashi", name: "Yankwashi" },
    ],
    "kaduna": [
      { id: "kaduna-birnin-gwari", name: "Birnin Gwari" },
      { id: "kaduna-chikun", name: "Chikun" },
      { id: "kaduna-giwa", name: "Giwa" },
      { id: "kaduna-igabi", name: "Igabi" },
      { id: "kaduna-ikara", name: "Ikara" },
      { id: "kaduna-jaba", name: "Jaba" },
      { id: "kaduna-jema-a", name: "Jema'a" },
      { id: "kaduna-kachia", name: "Kachia" },
      { id: "kaduna-kaduna-north", name: "Kaduna North" },
      { id: "kaduna-kaduna-south", name: "Kaduna South" },
      { id: "kaduna-kagarko", name: "Kagarko" },
      { id: "kaduna-kajuru", name: "Kajuru" },
      { id: "kaduna-kaura", name: "Kaura" },
      { id: "kaduna-kauru", name: "Kauru" },
      { id: "kaduna-kubau", name: "Kubau" },
      { id: "kaduna-kudan", name: "Kudan" },
      { id: "kaduna-lere", name: "Lere" },
      { id: "kaduna-makarfi", name: "Makarfi" },
      { id: "kaduna-sabon-gari", name: "Sabon Gari" },
      { id: "kaduna-sanga", name: "Sanga" },
      { id: "kaduna-soba", name: "Soba" },
      { id: "kaduna-zangon-kataf", name: "Zangon Kataf" },
      { id: "kaduna-zaria", name: "Zaria" },
    ],
    "kano": [
      { id: "kano-ajingi", name: "Ajingi" },
      { id: "kano-albasu", name: "Albasu" },
      { id: "kano-bagwai", name: "Bagwai" },
      { id: "kano-bebeji", name: "Bebeji" },
      { id: "kano-bichi", name: "Bichi" },
      { id: "kano-bunkure", name: "Bunkure" },
      { id: "kano-dala", name: "Dala" },
      { id: "kano-dambatta", name: "Dambatta" },
      { id: "kano-dawakin-kudu", name: "Dawakin Kudu" },
      { id: "kano-dawakin-tofa", name: "Dawakin Tofa" },
      { id: "kano-doguwa", name: "Doguwa" },
      { id: "kano-fagge", name: "Fagge" },
      { id: "kano-gabasawa", name: "Gabasawa" },
      { id: "kano-garko", name: "Garko" },
      { id: "kano-garun-mallam", name: "Garun Mallam" },
      { id: "kano-gaya", name: "Gaya" },
      { id: "kano-gezawa", name: "Gezawa" },
      { id: "kano-gwale", name: "Gwale" },
      { id: "kano-gwarzo", name: "Gwarzo" },
      { id: "kano-kabo", name: "Kabo" },
      { id: "kano-kano-municipal", name: "Kano Municipal" },
      { id: "kano-karaye", name: "Karaye" },
      { id: "kano-kibiya", name: "Kibiya" },
      { id: "kano-kiru", name: "Kiru" },
      { id: "kano-kumbotso", name: "Kumbotso" },
      { id: "kano-kunchi", name: "Kunchi" },
      { id: "kano-kura", name: "Kura" },
      { id: "kano-madobi", name: "Madobi" },
      { id: "kano-makoda", name: "Makoda" },
      { id: "kano-minjibir", name: "Minjibir" },
      { id: "kano-nasarawa", name: "Nasarawa" },
      { id: "kano-rano", name: "Rano" },
      { id: "kano-rimin-gado", name: "Rimin Gado" },
      { id: "kano-rogo", name: "Rogo" },
      { id: "kano-shanono", name: "Shanono" },
      { id: "kano-sumaila", name: "Sumaila" },
      { id: "kano-takai", name: "Takai" },
      { id: "kano-tarauni", name: "Tarauni" },
      { id: "kano-tofa", name: "Tofa" },
      { id: "kano-tsanyawa", name: "Tsanyawa" },
      { id: "kano-tudun-wada", name: "Tudun Wada" },
      { id: "kano-ungogo", name: "Ungogo" },
      { id: "kano-warawa", name: "Warawa" },
      { id: "kano-wudil", name: "Wudil" },
    ],
    "katsina": [
      { id: "katsina-bakori", name: "Bakori" },
      { id: "katsina-batagarawa", name: "Batagarawa" },
      { id: "katsina-batsari", name: "Batsari" },
      { id: "katsina-baure", name: "Baure" },
      { id: "katsina-bindawa", name: "Bindawa" },
      { id: "katsina-charanchi", name: "Charanchi" },
      { id: "katsina-dan-musa", name: "Dan Musa" },
      { id: "katsina-dandume", name: "Dandume" },
      { id: "katsina-danja", name: "Danja" },
      { id: "katsina-daura", name: "Daura" },
      { id: "katsina-dutsi", name: "Dutsi" },
      { id: "katsina-dutsin-ma", name: "Dutsin Ma" },
      { id: "katsina-faskari", name: "Faskari" },
      { id: "katsina-funtua", name: "Funtua" },
      { id: "katsina-ingawa", name: "Ingawa" },
      { id: "katsina-jibia", name: "Jibia" },
      { id: "katsina-kafur", name: "Kafur" },
      { id: "katsina-kaita", name: "Kaita" },
      { id: "katsina-kankara", name: "Kankara" },
      { id: "katsina-kankia", name: "Kankia" },
      { id: "katsina-katsina", name: "Katsina" },
      { id: "katsina-kurfi", name: "Kurfi" },
      { id: "katsina-kusada", name: "Kusada" },
      { id: "katsina-mai-adua", name: "Mai'Adua" },
      { id: "katsina-malumfashi", name: "Malumfashi" },
      { id: "katsina-mani", name: "Mani" },
      { id: "katsina-mashi", name: "Mashi" },
      { id: "katsina-matazu", name: "Matazu" },
      { id: "katsina-musawa", name: "Musawa" },
      { id: "katsina-rimi", name: "Rimi" },
      { id: "katsina-sabuwa", name: "Sabuwa" },
      { id: "katsina-safana", name: "Safana" },
      { id: "katsina-sandamu", name: "Sandamu" },
      { id: "katsina-zango", name: "Zango" },
    ],
    "kebbi": [
      { id: "kebbi-aleiro", name: "Aleiro" },
      { id: "kebbi-arewa-dandi", name: "Arewa Dandi" },
      { id: "kebbi-argungu", name: "Argungu" },
      { id: "kebbi-augie", name: "Augie" },
      { id: "kebbi-bagudo", name: "Bagudo" },
      { id: "kebbi-birnin-kebbi", name: "Birnin Kebbi" },
      { id: "kebbi-bunza", name: "Bunza" },
      { id: "kebbi-dandi", name: "Dandi" },
      { id: "kebbi-fakai", name: "Fakai" },
      { id: "kebbi-gwandu", name: "Gwandu" },
      { id: "kebbi-jega", name: "Jega" },
      { id: "kebbi-kalgo", name: "Kalgo" },
      { id: "kebbi-koko-besse", name: "Koko/Besse" },
      { id: "kebbi-maiyama", name: "Maiyama" },
      { id: "kebbi-ngaski", name: "Ngaski" },
      { id: "kebbi-sakaba", name: "Sakaba" },
      { id: "kebbi-shanga", name: "Shanga" },
      { id: "kebbi-suru", name: "Suru" },
      { id: "kebbi-wasagu-danko", name: "Wasagu/Danko" },
      { id: "kebbi-yauri", name: "Yauri" },
      { id: "kebbi-zuru", name: "Zuru" },
    ],
    "kogi": [
      { id: "kogi-adavi", name: "Adavi" },
      { id: "kogi-ajaokuta", name: "Ajaokuta" },
      { id: "kogi-ankpa", name: "Ankpa" },
      { id: "kogi-bassa", name: "Bassa" },
      { id: "kogi-dekina", name: "Dekina" },
      { id: "kogi-ibaji", name: "Ibaji" },
      { id: "kogi-idah", name: "Idah" },
      { id: "kogi-igalamela-odolu", name: "Igalamela Odolu" },
      { id: "kogi-ijumu", name: "Ijumu" },
      { id: "kogi-kabba-bunu", name: "Kabba/Bunu" },
      { id: "kogi-kogi", name: "Kogi" },
      { id: "kogi-lokoja", name: "Lokoja" },
      { id: "kogi-mopa-muro", name: "Mopa Muro" },
      { id: "kogi-ofu", name: "Ofu" },
      { id: "kogi-ogori-magongo", name: "Ogori/Magongo" },
      { id: "kogi-okehi", name: "Okehi" },
      { id: "kogi-okene", name: "Okene" },
      { id: "kogi-olamaboro", name: "Olamaboro" },
      { id: "kogi-omala", name: "Omala" },
      { id: "kogi-yagba-east", name: "Yagba East" },
      { id: "kogi-yagba-west", name: "Yagba West" },
    ],
    "kwara": [
      { id: "kwara-asa", name: "Asa" },
      { id: "kwara-baruten", name: "Baruten" },
      { id: "kwara-edu", name: "Edu" },
      { id: "kwara-ekiti", name: "Ekiti" },
      { id: "kwara-ifelodun", name: "Ifelodun" },
      { id: "kwara-ilorin-east", name: "Ilorin East" },
      { id: "kwara-ilorin-south", name: "Ilorin South" },
      { id: "kwara-ilorin-west", name: "Ilorin West" },
      { id: "kwara-irepodun", name: "Irepodun" },
      { id: "kwara-isin", name: "Isin" },
      { id: "kwara-kaiama", name: "Kaiama" },
      { id: "kwara-moro", name: "Moro" },
      { id: "kwara-offa", name: "Offa" },
      { id: "kwara-oke-ero", name: "Oke Ero" },
      { id: "kwara-oyun", name: "Oyun" },
      { id: "kwara-pategi", name: "Pategi" },
    ],
    "lagos": [
      { id: "lagos-agege", name: "Agege" },
      { id: "lagos-ajeromi-ifelodun", name: "Ajeromi-Ifelodun" },
      { id: "lagos-alimosho", name: "Alimosho" },
      { id: "lagos-amuwo-odofin", name: "Amuwo-Odofin" },
      { id: "lagos-apapa", name: "Apapa" },
      { id: "lagos-badagry", name: "Badagry" },
      { id: "lagos-epe", name: "Epe" },
      { id: "lagos-eti-osa", name: "Eti-Osa" },
      { id: "lagos-ibeju-lekki", name: "Ibeju-Lekki" },
      { id: "lagos-ifako-ijaiye", name: "Ifako-Ijaiye" },
      { id: "lagos-ikeja", name: "Ikeja" },
      { id: "lagos-ikorodu", name: "Ikorodu" },
      { id: "lagos-kosofe", name: "Kosofe" },
      { id: "lagos-lagos-island", name: "Lagos Island" },
      { id: "lagos-lagos-mainland", name: "Lagos Mainland" },
      { id: "lagos-mushin", name: "Mushin" },
      { id: "lagos-ojo", name: "Ojo" },
      { id: "lagos-oshodi-isolo", name: "Oshodi-Isolo" },
      { id: "lagos-shomolu", name: "Shomolu" },
      { id: "lagos-surulere", name: "Surulere" },
    ],
    "nasarawa": [
      { id: "nasarawa-akwanga", name: "Akwanga" },
      { id: "nasarawa-awe", name: "Awe" },
      { id: "nasarawa-doma", name: "Doma" },
      { id: "nasarawa-karu", name: "Karu" },
      { id: "nasarawa-keana", name: "Keana" },
      { id: "nasarawa-keffi", name: "Keffi" },
      { id: "nasarawa-kokona", name: "Kokona" },
      { id: "nasarawa-lafia", name: "Lafia" },
      { id: "nasarawa-nasarawa", name: "Nasarawa" },
      { id: "nasarawa-nasarawa-eggon", name: "Nasarawa Eggon" },
      { id: "nasarawa-obi", name: "Obi" },
      { id: "nasarawa-toto", name: "Toto" },
      { id: "nasarawa-wamba", name: "Wamba" },
    ],
    "niger": [
      { id: "niger-agaie", name: "Agaie" },
      { id: "niger-agwara", name: "Agwara" },
      { id: "niger-bida", name: "Bida" },
      { id: "niger-borgu", name: "Borgu" },
      { id: "niger-bosso", name: "Bosso" },
      { id: "niger-chanchaga", name: "Chanchaga" },
      { id: "niger-edati", name: "Edati" },
      { id: "niger-gbako", name: "Gbako" },
      { id: "niger-gurara", name: "Gurara" },
      { id: "niger-katcha", name: "Katcha" },
      { id: "niger-kontagora", name: "Kontagora" },
      { id: "niger-lapai", name: "Lapai" },
      { id: "niger-lavun", name: "Lavun" },
      { id: "niger-magama", name: "Magama" },
      { id: "niger-mariga", name: "Mariga" },
      { id: "niger-mashegu", name: "Mashegu" },
      { id: "niger-mokwa", name: "Mokwa" },
      { id: "niger-munya", name: "Munya" },
      { id: "niger-paikoro", name: "Paikoro" },
      { id: "niger-rafi", name: "Rafi" },
      { id: "niger-rijau", name: "Rijau" },
      { id: "niger-shiroro", name: "Shiroro" },
      { id: "niger-suleja", name: "Suleja" },
      { id: "niger-tafa", name: "Tafa" },
      { id: "niger-wushishi", name: "Wushishi" },
    ],
    "ogun": [
      { id: "ogun-abeokuta-north", name: "Abeokuta North" },
      { id: "ogun-abeokuta-south", name: "Abeokuta South" },
      { id: "ogun-ado-odo-ota", name: "Ado-Odo/Ota" },
      { id: "ogun-ewekoro", name: "Ewekoro" },
      { id: "ogun-ifo", name: "Ifo" },
      { id: "ogun-ijebu-east", name: "Ijebu East" },
      { id: "ogun-ijebu-north", name: "Ijebu North" },
      { id: "ogun-ijebu-north-east", name: "Ijebu North East" },
      { id: "ogun-ijebu-ode", name: "Ijebu Ode" },
      { id: "ogun-ikenne", name: "Ikenne" },
      { id: "ogun-imeko-afon", name: "Imeko Afon" },
      { id: "ogun-ipokia", name: "Ipokia" },
      { id: "ogun-obafemi-owode", name: "Obafemi Owode" },
      { id: "ogun-odeda", name: "Odeda" },
      { id: "ogun-odogbolu", name: "Odogbolu" },
      { id: "ogun-ogun-waterside", name: "Ogun Waterside" },
      { id: "ogun-remo-north", name: "Remo North" },
      { id: "ogun-sagamu", name: "Sagamu" },
      { id: "ogun-yewa-north", name: "Yewa North" },
      { id: "ogun-yewa-south", name: "Yewa South" },
    ],
    "ondo": [
      { id: "ondo-akoko-north-east", name: "Akoko North-East" },
      { id: "ondo-akoko-north-west", name: "Akoko North-West" },
      { id: "ondo-akoko-south-east", name: "Akoko South-East" },
      { id: "ondo-akoko-south-west", name: "Akoko South-West" },
      { id: "ondo-akure-north", name: "Akure North" },
      { id: "ondo-akure-south", name: "Akure South" },
      { id: "ondo-ese-odo", name: "Ese Odo" },
      { id: "ondo-idanre", name: "Idanre" },
      { id: "ondo-ifedore", name: "Ifedore" },
      { id: "ondo-ilaje", name: "Ilaje" },
      { id: "ondo-ile-oluji-okeigbo", name: "Ile Oluji/Okeigbo" },
      { id: "ondo-irele", name: "Irele" },
      { id: "ondo-odigbo", name: "Odigbo" },
      { id: "ondo-okitipupa", name: "Okitipupa" },
      { id: "ondo-ondo-east", name: "Ondo East" },
      { id: "ondo-ondo-west", name: "Ondo West" },
      { id: "ondo-ose", name: "Ose" },
      { id: "ondo-owo", name: "Owo" },
    ],
    "osun": [
      { id: "osun-aiyedade", name: "Aiyedade" },
      { id: "osun-aiyedire", name: "Aiyedire" },
      { id: "osun-atakumosa-east", name: "Atakumosa East" },
      { id: "osun-atakumosa-west", name: "Atakumosa West" },
      { id: "osun-boluwaduro", name: "Boluwaduro" },
      { id: "osun-boripe", name: "Boripe" },
      { id: "osun-ede-north", name: "Ede North" },
      { id: "osun-ede-south", name: "Ede South" },
      { id: "osun-egbedore", name: "Egbedore" },
      { id: "osun-ejigbo", name: "Ejigbo" },
      { id: "osun-ife-central", name: "Ife Central" },
      { id: "osun-ife-east", name: "Ife East" },
      { id: "osun-ife-north", name: "Ife North" },
      { id: "osun-ife-south", name: "Ife South" },
      { id: "osun-ifedayo", name: "Ifedayo" },
      { id: "osun-ifelodun", name: "Ifelodun" },
      { id: "osun-ila", name: "Ila" },
      { id: "osun-ilesa-east", name: "Ilesa East" },
      { id: "osun-ilesa-west", name: "Ilesa West" },
      { id: "osun-irepodun", name: "Irepodun" },
      { id: "osun-irewole", name: "Irewole" },
      { id: "osun-isokan", name: "Isokan" },
      { id: "osun-iwo", name: "Iwo" },
      { id: "osun-obokun", name: "Obokun" },
      { id: "osun-odo-otin", name: "Odo Otin" },
      { id: "osun-ola-oluwa", name: "Ola Oluwa" },
      { id: "osun-olorunda", name: "Olorunda" },
      { id: "osun-oriade", name: "Oriade" },
      { id: "osun-orolu", name: "Orolu" },
      { id: "osun-osogbo", name: "Osogbo" },
    ],
    "oyo": [
      { id: "oyo-afijio", name: "Afijio" },
      { id: "oyo-akinyele", name: "Akinyele" },
      { id: "oyo-atiba", name: "Atiba" },
      { id: "oyo-atisbo", name: "Atisbo" },
      { id: "oyo-egbeda", name: "Egbeda" },
      { id: "oyo-ibadan-north", name: "Ibadan North" },
      { id: "oyo-ibadan-north-east", name: "Ibadan North-East" },
      { id: "oyo-ibadan-north-west", name: "Ibadan North-West" },
      { id: "oyo-ibadan-south-east", name: "Ibadan South-East" },
      { id: "oyo-ibadan-south-west", name: "Ibadan South-West" },
      { id: "oyo-ibarapa-central", name: "Ibarapa Central" },
      { id: "oyo-ibarapa-east", name: "Ibarapa East" },
      { id: "oyo-ibarapa-north", name: "Ibarapa North" },
      { id: "oyo-ido", name: "Ido" },
      { id: "oyo-irepo", name: "Irepo" },
      { id: "oyo-iseyin", name: "Iseyin" },
      { id: "oyo-itesiwaju", name: "Itesiwaju" },
      { id: "oyo-iwajowa", name: "Iwajowa" },
      { id: "oyo-kajola", name: "Kajola" },
      { id: "oyo-lagelu", name: "Lagelu" },
      { id: "oyo-ogbomosho-north", name: "Ogbomosho North" },
      { id: "oyo-ogbomosho-south", name: "Ogbomosho South" },
      { id: "oyo-ogo-oluwa", name: "Ogo Oluwa" },
      { id: "oyo-olorunsogo", name: "Olorunsogo" },
      { id: "oyo-oluyole", name: "Oluyole" },
      { id: "oyo-ona-ara", name: "Ona Ara" },
      { id: "oyo-orelope", name: "Orelope" },
      { id: "oyo-ori-ire", name: "Ori Ire" },
      { id: "oyo-oyo-east", name: "Oyo East" },
      { id: "oyo-oyo-west", name: "Oyo West" },
      { id: "oyo-saki-east", name: "Saki East" },
      { id: "oyo-saki-west", name: "Saki West" },
      { id: "oyo-surulere", name: "Surulere" },
    ],
    "plateau": [
      { id: "plateau-barkin-ladi", name: "Barkin Ladi" },
      { id: "plateau-bassa", name: "Bassa" },
      { id: "plateau-bokkos", name: "Bokkos" },
      { id: "plateau-jos-east", name: "Jos East" },
      { id: "plateau-jos-north", name: "Jos North" },
      { id: "plateau-jos-south", name: "Jos South" },
      { id: "plateau-kanam", name: "Kanam" },
      { id: "plateau-kanke", name: "Kanke" },
      { id: "plateau-langtang-north", name: "Langtang North" },
      { id: "plateau-langtang-south", name: "Langtang South" },
      { id: "plateau-mangu", name: "Mangu" },
      { id: "plateau-mikang", name: "Mikang" },
      { id: "plateau-pankshin", name: "Pankshin" },
      { id: "plateau-qua-an-pan", name: "Qua'an Pan" },
      { id: "plateau-riyom", name: "Riyom" },
      { id: "plateau-shendam", name: "Shendam" },
      { id: "plateau-wase", name: "Wase" },
    ],
    "rivers": [
      { id: "rivers-abua-odual", name: "Abua/Odual" },
      { id: "rivers-ahoada-east", name: "Ahoada East" },
      { id: "rivers-ahoada-west", name: "Ahoada West" },
      { id: "rivers-akuku-toru", name: "Akuku-Toru" },
      { id: "rivers-andoni", name: "Andoni" },
      { id: "rivers-asari-toru", name: "Asari-Toru" },
      { id: "rivers-bonny", name: "Bonny" },
      { id: "rivers-degema", name: "Degema" },
      { id: "rivers-eleme", name: "Eleme" },
      { id: "rivers-emohua", name: "Emohua" },
      { id: "rivers-etche", name: "Etche" },
      { id: "rivers-gokana", name: "Gokana" },
      { id: "rivers-ikwerre", name: "Ikwerre" },
      { id: "rivers-khana", name: "Khana" },
      { id: "rivers-obio-akpor", name: "Obio/Akpor" },
      { id: "rivers-ogba-egbema-ndoni", name: "Ogba/Egbema/Ndoni" },
      { id: "rivers-ogu-bolo", name: "Ogu/Bolo" },
      { id: "rivers-okrika", name: "Okrika" },
      { id: "rivers-omuma", name: "Omuma" },
      { id: "rivers-opobo-nkoro", name: "Opobo/Nkoro" },
      { id: "rivers-oyigbo", name: "Oyigbo" },
      { id: "rivers-port-harcourt", name: "Port Harcourt" },
      { id: "rivers-tai", name: "Tai" },
    ],
    "sokoto": [
      { id: "sokoto-binji", name: "Binji" },
      { id: "sokoto-bodinga", name: "Bodinga" },
      { id: "sokoto-dange-shuni", name: "Dange Shuni" },
      { id: "sokoto-gada", name: "Gada" },
      { id: "sokoto-goronyo", name: "Goronyo" },
      { id: "sokoto-gudu", name: "Gudu" },
      { id: "sokoto-gwadabawa", name: "Gwadabawa" },
      { id: "sokoto-illela", name: "Illela" },
      { id: "sokoto-isa", name: "Isa" },
      { id: "sokoto-kebbe", name: "Kebbe" },
      { id: "sokoto-kware", name: "Kware" },
      { id: "sokoto-rabah", name: "Rabah" },
      { id: "sokoto-sabon-birni", name: "Sabon Birni" },
      { id: "sokoto-shagari", name: "Shagari" },
      { id: "sokoto-silame", name: "Silame" },
      { id: "sokoto-sokoto-north", name: "Sokoto North" },
      { id: "sokoto-sokoto-south", name: "Sokoto South" },
      { id: "sokoto-tambuwal", name: "Tambuwal" },
      { id: "sokoto-tangaza", name: "Tangaza" },
      { id: "sokoto-tureta", name: "Tureta" },
      { id: "sokoto-wamako", name: "Wamako" },
      { id: "sokoto-wurno", name: "Wurno" },
      { id: "sokoto-yabo", name: "Yabo" },
    ],
    "taraba": [
      { id: "taraba-ardo-kola", name: "Ardo Kola" },
      { id: "taraba-bali", name: "Bali" },
      { id: "taraba-donga", name: "Donga" },
      { id: "taraba-gashaka", name: "Gashaka" },
      { id: "taraba-gassol", name: "Gassol" },
      { id: "taraba-ibi", name: "Ibi" },
      { id: "taraba-jalingo", name: "Jalingo" },
      { id: "taraba-karim-lamido", name: "Karim Lamido" },
      { id: "taraba-kumi", name: "Kumi" },
      { id: "taraba-lau", name: "Lau" },
      { id: "taraba-sardauna", name: "Sardauna" },
      { id: "taraba-takum", name: "Takum" },
      { id: "taraba-ussa", name: "Ussa" },
      { id: "taraba-wukari", name: "Wukari" },
      { id: "taraba-yorro", name: "Yorro" },
      { id: "taraba-zing", name: "Zing" },
    ],
    "yobe": [
      { id: "yobe-bade", name: "Bade" },
      { id: "yobe-bursari", name: "Bursari" },
      { id: "yobe-damaturu", name: "Damaturu" },
      { id: "yobe-fika", name: "Fika" },
      { id: "yobe-fune", name: "Fune" },
      { id: "yobe-geidam", name: "Geidam" },
      { id: "yobe-gujba", name: "Gujba" },
      { id: "yobe-gulani", name: "Gulani" },
      { id: "yobe-jakusko", name: "Jakusko" },
      { id: "yobe-karasuwa", name: "Karasuwa" },
      { id: "yobe-machina", name: "Machina" },
      { id: "yobe-nangere", name: "Nangere" },
      { id: "yobe-nguru", name: "Nguru" },
      { id: "yobe-potiskum", name: "Potiskum" },
      { id: "yobe-tarmuwa", name: "Tarmuwa" },
      { id: "yobe-yunusari", name: "Yunusari" },
      { id: "yobe-yusufari", name: "Yusufari" },
    ],
    "zamfara": [
      { id: "zamfara-anka", name: "Anka" },
      { id: "zamfara-bakura", name: "Bakura" },
      { id: "zamfara-birnin-magaji-kiyaw", name: "Birnin Magaji/Kiyaw" },
      { id: "zamfara-bukkuyum", name: "Bukkuyum" },
      { id: "zamfara-bungudu", name: "Bungudu" },
      { id: "zamfara-gummi", name: "Gummi" },
      { id: "zamfara-gusau", name: "Gusau" },
      { id: "zamfara-kaura-namoda", name: "Kaura Namoda" },
      { id: "zamfara-maradun", name: "Maradun" },
      { id: "zamfara-maru", name: "Maru" },
      { id: "zamfara-shinkafi", name: "Shinkafi" },
      { id: "zamfara-talata-mafara", name: "Talata Mafara" },
      { id: "zamfara-tsafe", name: "Tsafe" },
      { id: "zamfara-zurmi", name: "Zurmi" },
    ],
    "fct": [
      { id: "fct-abaji", name: "Abaji" },
      { id: "fct-bwari", name: "Bwari" },
      { id: "fct-gwagwalada", name: "Gwagwalada" },
      { id: "fct-kuje", name: "Kuje" },
      { id: "fct-kwali", name: "Kwali" },
      { id: "fct-municipal-area-council", name: "Municipal Area Council" },
    ],
  },
};
