// AUTO-GENERATED by scripts/gen-docs-manifest.mjs, do not edit by hand.
// Regenerate with: node scripts/gen-docs-manifest.mjs

export interface DocsManifestEntry {
  name: string;
  slug: string;
  description: string;
}

export const docsManifest: DocsManifestEntry[] = [
  {
    "name": "Accordion",
    "slug": "accordion",
    "description": ""
  },
  {
    "name": "Alert",
    "slug": "alert",
    "description": ""
  },
  {
    "name": "Alert Dialog",
    "slug": "alert-dialog",
    "description": ""
  },
  {
    "name": "Avatar",
    "slug": "avatar",
    "description": ""
  },
  {
    "name": "Avatar Group",
    "slug": "avatar-group",
    "description": ""
  },
  {
    "name": "Badge",
    "slug": "badge",
    "description": ""
  },
  {
    "name": "Breadcrumb",
    "slug": "breadcrumb",
    "description": ""
  },
  {
    "name": "Button",
    "slug": "button",
    "description": ""
  },
  {
    "name": "Button Group",
    "slug": "button-group",
    "description": ""
  },
  {
    "name": "Card",
    "slug": "card",
    "description": ""
  },
  {
    "name": "Checkbox",
    "slug": "checkbox",
    "description": ""
  },
  {
    "name": "Collapsible",
    "slug": "collapsible",
    "description": "Collapsible: expand/collapse section built on Radix Collapsible primitive."
  },
  {
    "name": "Combobox",
    "slug": "combobox",
    "description": ""
  },
  {
    "name": "Command",
    "slug": "command",
    "description": ""
  },
  {
    "name": "Context Menu",
    "slug": "context-menu",
    "description": ""
  },
  {
    "name": "Dialog",
    "slug": "dialog",
    "description": ""
  },
  {
    "name": "Dropdown Menu",
    "slug": "dropdown-menu",
    "description": ""
  },
  {
    "name": "Empty State",
    "slug": "empty-state",
    "description": ""
  },
  {
    "name": "Hover Card",
    "slug": "hover-card",
    "description": ""
  },
  {
    "name": "Input",
    "slug": "input",
    "description": ""
  },
  {
    "name": "Input Otp",
    "slug": "input-otp",
    "description": ""
  },
  {
    "name": "Kbd",
    "slug": "kbd",
    "description": ""
  },
  {
    "name": "Label",
    "slug": "label",
    "description": ""
  },
  {
    "name": "Menubar",
    "slug": "menubar",
    "description": ""
  },
  {
    "name": "Navbar",
    "slug": "navbar",
    "description": "Active-state matching for plain anchors:"
  },
  {
    "name": "Navigation Menu",
    "slug": "navigation-menu",
    "description": ""
  },
  {
    "name": "Notification Bell",
    "slug": "notification-bell",
    "description": "@deprecated Use NotificationDrawer instead: it supports the same API plus"
  },
  {
    "name": "Notification Drawer",
    "slug": "notification-drawer",
    "description": ""
  },
  {
    "name": "Pagination",
    "slug": "pagination",
    "description": ""
  },
  {
    "name": "Popover",
    "slug": "popover",
    "description": ""
  },
  {
    "name": "Progress",
    "slug": "progress",
    "description": ""
  },
  {
    "name": "Radio Group",
    "slug": "radio-group",
    "description": ""
  },
  {
    "name": "Scroll Area",
    "slug": "scroll-area",
    "description": ""
  },
  {
    "name": "Select",
    "slug": "select",
    "description": ""
  },
  {
    "name": "Separator",
    "slug": "separator",
    "description": ""
  },
  {
    "name": "Sheet",
    "slug": "sheet",
    "description": ""
  },
  {
    "name": "Skeleton",
    "slug": "skeleton",
    "description": ""
  },
  {
    "name": "Slider",
    "slug": "slider",
    "description": ""
  },
  {
    "name": "Sonner",
    "slug": "sonner",
    "description": "Toaster: styled sonner toast provider."
  },
  {
    "name": "Spinner",
    "slug": "spinner",
    "description": ""
  },
  {
    "name": "Switch",
    "slug": "switch",
    "description": ""
  },
  {
    "name": "Table",
    "slug": "table",
    "description": ""
  },
  {
    "name": "Tabs",
    "slug": "tabs",
    "description": ""
  },
  {
    "name": "Textarea",
    "slug": "textarea",
    "description": ""
  },
  {
    "name": "Toggle",
    "slug": "toggle",
    "description": ""
  },
  {
    "name": "Toggle Group",
    "slug": "toggle-group",
    "description": ""
  },
  {
    "name": "Tooltip",
    "slug": "tooltip",
    "description": ""
  },
  {
    "name": "Icon",
    "slug": "icon",
    "description": "Semantic icon registry: built-in lucide map, registerIcon overrides, IconProvider per-domain overrides."
  },
  {
    "name": "Theme",
    "slug": "theme",
    "description": "ThemeProvider / useTheme / ThemeToggle: light, dark, and system theming."
  }
];
